"""
One-off analysis: for the solver's top-N moves, report any 5-line / open-5
threats they create for the opponent, and the opponent's best possible response
given the remaining tile pool.

A "Qwirkle threat" = after my move, there exists a line of 5 tiles (same color
or same shape) with at least one adjacent empty cell legal for the missing 6th
tile. The opponent who holds that tile scores 12 (6-line + 6 bonus).

A "4-open" line is a softer setup: a 4-tile line with open endpoints that can
become an open-5 with one extension.

"Opponent best response" = max score across all legal 1-to-N-tile placements
the opponent could make, where their hypothetical hand = every tile type still
unaccounted-for (3-per-type minus board minus my hand). Capped at 3 tiles per
opponent move for tractability (still catches Qwirkle = 3-tile extension of a
3-line column).
"""
from collections import Counter
from pathlib import Path

from qwirkle_solver import (
    QwirkleEngine,
    Tile,
    calculate_score_multi,
    generate_all_multi_moves,
    generate_connected_segments,
    get_line_on_board,
    iter_tile_sequences,
    load_game_state,
)

ALL_COLORS = ["red", "orange", "yellow", "green", "blue", "purple"]
ALL_SHAPES = ["circle", "square", "diamond", "clover", "crossx", "star"]


def line_through(board, x, y, axis):
    """Return list of (pos, tile) for the contiguous line through (x,y) on axis,
    including the tile at (x,y) itself. Assumes (x,y) is in board."""
    if axis == "horizontal":
        dirs = [(1, 0), (-1, 0)]
        key = 0
    else:
        dirs = [(0, 1), (0, -1)]
        key = 1

    cells = [((x, y), board[(x, y)])]
    for dx, dy in dirs:
        cx, cy = x + dx, y + dy
        while (cx, cy) in board:
            cells.append(((cx, cy), board[(cx, cy)]))
            cx += dx
            cy += dy
    cells.sort(key=lambda c: c[0][key])
    return cells


def line_signature(tiles):
    """Return ('color', color, missing_shapes) or ('shape', shape, missing_colors)
    or None if the line is mixed (shouldn't happen in a legal board)."""
    colors = {t.color for t in tiles}
    shapes = {t.shape for t in tiles}
    if len(colors) == 1:
        c = next(iter(colors))
        return ("color", c, [s for s in ALL_SHAPES if s not in shapes])
    if len(shapes) == 1:
        s = next(iter(shapes))
        return ("shape", s, [c for c in ALL_COLORS if c not in colors])
    return None


def open_endpoints(board, line_cells, axis):
    """Return list of empty endpoint cells just past either end of the line."""
    if axis == "horizontal":
        y = line_cells[0][0][1]
        min_x = line_cells[0][0][0]
        max_x = line_cells[-1][0][0]
        ends = [(min_x - 1, y), (max_x + 1, y)]
    else:
        x = line_cells[0][0][0]
        min_y = line_cells[0][0][1]
        max_y = line_cells[-1][0][1]
        ends = [(x, min_y - 1), (x, max_y + 1)]
    return [e for e in ends if e not in board]


def compute_remaining_pool(board, hand):
    """Tiles still unaccounted-for: 3 of every type, minus board, minus my hand."""
    pool: Counter = Counter()
    for c in ALL_COLORS:
        for s in ALL_SHAPES:
            pool[Tile(color=c, shape=s)] = 3
    for tile in board.values():
        pool[tile] -= 1
    for tile, n in hand.items():
        pool[tile] -= n
    return Counter({t: c for t, c in pool.items() if c > 0})


def opponent_best_responses(engine, my_placements, my_hand,
                             max_len=3, top_k=5):
    """After applying my move, return opponent's top-k highest-scoring legal
    moves (up to max_len tiles) using any tile from the remaining pool."""
    after_board = engine.board.copy()
    for pos, tile in my_placements:
        after_board[pos] = tile
    after_engine = QwirkleEngine()
    after_engine.load_board_state(after_board)

    my_remaining = my_hand.copy()
    for _, tile in my_placements:
        my_remaining[tile] -= 1
    pool = compute_remaining_pool(after_board, my_remaining)

    # One of each remaining tile type — duplicates don't add legal placements
    # within a single line (would violate uniqueness rule).
    opp_hand: Counter = Counter({t: 1 for t in pool})

    segments = generate_connected_segments(after_engine, max_len=max_len)
    results = []
    for segment in segments:
        for sequence in iter_tile_sequences(opp_hand, len(segment)):
            placements = list(zip(segment, sequence))
            score = calculate_score_multi(after_engine, placements)
            if score is not None:
                results.append((score, placements))
    results.sort(key=lambda r: r[0], reverse=True)

    # Dedup by (frozenset of placements) since the same placement can be
    # generated by different segment orientations.
    seen = set()
    unique = []
    for score, placements in results:
        key = frozenset((pos, (t.color, t.shape)) for pos, t in placements)
        if key in seen:
            continue
        seen.add(key)
        unique.append((score, placements))
        if len(unique) >= top_k:
            break
    return unique, pool


def format_placements(placements):
    return ", ".join(f"{pos}={t.color[0]}{t.shape[:2]}" for pos, t in placements)


def analyze_move(engine, placements, rank, score, my_hand=None):
    print(f"\n{'='*72}")
    print(f"Rank {rank}: {score} points")
    for pos, tile in placements:
        print(f"  place {pos}: {tile.color}-{tile.shape}")

    temp = engine.board.copy()
    for pos, tile in placements:
        temp[pos] = tile

    new_positions = {pos for pos, _ in placements}
    seen_lines = set()
    threats_5 = []  # (line_cells, axis, missing tile, open endpoints)
    setups_4 = []

    for pos in new_positions:
        x, y = pos
        for axis in ["horizontal", "vertical"]:
            cells = line_through(temp, x, y, axis)
            if len(cells) < 4:
                continue
            key = (axis, tuple(c[0] for c in cells))
            if key in seen_lines:
                continue
            seen_lines.add(key)

            tiles_only = [t for _, t in cells]
            sig = line_signature(tiles_only)
            if sig is None:
                continue
            kind, value, missing = sig
            ends = open_endpoints(temp, cells, axis)
            if not ends:
                continue

            if len(cells) == 5:
                threats_5.append((cells, axis, kind, value, missing, ends))
            elif len(cells) == 4:
                setups_4.append((cells, axis, kind, value, missing, ends))

    if threats_5:
        print("  ** DIRECT QWIRKLE THREAT (opponent scores 12) **")
        for cells, axis, kind, value, missing, ends in threats_5:
            tile_strs = [f"{t.color[0]}{t.shape[:2]}" for _, t in cells]
            print(f"    {axis} 5-line [{value} {kind}]: " + " ".join(tile_strs))
            print(f"      open ends: {ends}")
            print(f"      opponent needs ({kind}={value}, missing {kind[0]}): {missing}")
    else:
        print("  No direct open-5 (Qwirkle) threat.")

    if setups_4:
        print("  4-line setups (could become open-5 next opponent turn):")
        for cells, axis, kind, value, missing, ends in setups_4:
            tile_strs = [f"{t.color[0]}{t.shape[:2]}" for _, t in cells]
            print(f"    {axis} 4-line [{value} {kind}]: " + " ".join(tile_strs))
            print(f"      open ends: {ends} | missing: {missing}")
    else:
        print("  No 4-open setups.")

    if my_hand is not None:
        responses, pool = opponent_best_responses(engine, placements, my_hand)
        print(f"  Opponent best responses (pool: {sum(pool.values())} tiles, "
              f"{len(pool)} distinct types; capped at 3-tile opp moves):")
        if not responses:
            print("    (no legal opponent move found)")
        for s, p in responses:
            print(f"    {s} pts -> {format_placements(p)}")


def main():
    engine = QwirkleEngine()
    state, hand = load_game_state(Path(__file__).parent / "game_state.json")
    engine.load_board_state(state)

    all_moves = generate_all_multi_moves(engine, hand)
    print(f"Total legal moves: {len(all_moves)}")
    if not all_moves:
        return

    top_score = all_moves[0][0]
    # Analyze every move that ties the top score
    top_tier = [(s, p) for s, p in all_moves if s == top_score]
    print(f"Top score: {top_score} ({len(top_tier)} move(s) tied)")

    n = min(len(top_tier), 6)
    for rank, (score, placements) in enumerate(top_tier[:n], start=1):
        analyze_move(engine, placements, rank, score, my_hand=hand)


if __name__ == "__main__":
    main()
